// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Vy4cheSlave/grpc_user-manager/internal/domain/task_crud"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTaskCrud creates a new instance of MockTaskCrud. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTaskCrud(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTaskCrud {
	mock := &MockTaskCrud{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTaskCrud is an autogenerated mock type for the TaskCrud type
type MockTaskCrud struct {
	mock.Mock
}

type MockTaskCrud_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTaskCrud) EXPECT() *MockTaskCrud_Expecter {
	return &MockTaskCrud_Expecter{mock: &_m.Mock}
}

// CreateTask provides a mock function for the type MockTaskCrud
func (_mock *MockTaskCrud) CreateTask(ctx context.Context, userId *string, title *string, description *string) (int, error) {
	ret := _mock.Called(ctx, userId, title, description)

	if len(ret) == 0 {
		panic("no return value specified for CreateTask")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *string, *string, *string) (int, error)); ok {
		return returnFunc(ctx, userId, title, description)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *string, *string, *string) int); ok {
		r0 = returnFunc(ctx, userId, title, description)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *string, *string, *string) error); ok {
		r1 = returnFunc(ctx, userId, title, description)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskCrud_CreateTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTask'
type MockTaskCrud_CreateTask_Call struct {
	*mock.Call
}

// CreateTask is a helper method to define mock.On call
//   - ctx context.Context
//   - userId *string
//   - title *string
//   - description *string
func (_e *MockTaskCrud_Expecter) CreateTask(ctx interface{}, userId interface{}, title interface{}, description interface{}) *MockTaskCrud_CreateTask_Call {
	return &MockTaskCrud_CreateTask_Call{Call: _e.mock.On("CreateTask", ctx, userId, title, description)}
}

func (_c *MockTaskCrud_CreateTask_Call) Run(run func(ctx context.Context, userId *string, title *string, description *string)) *MockTaskCrud_CreateTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *string
		if args[1] != nil {
			arg1 = args[1].(*string)
		}
		var arg2 *string
		if args[2] != nil {
			arg2 = args[2].(*string)
		}
		var arg3 *string
		if args[3] != nil {
			arg3 = args[3].(*string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockTaskCrud_CreateTask_Call) Return(taskId int, err error) *MockTaskCrud_CreateTask_Call {
	_c.Call.Return(taskId, err)
	return _c
}

func (_c *MockTaskCrud_CreateTask_Call) RunAndReturn(run func(ctx context.Context, userId *string, title *string, description *string) (int, error)) *MockTaskCrud_CreateTask_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTask provides a mock function for the type MockTaskCrud
func (_mock *MockTaskCrud) DeleteTask(ctx context.Context, taskId int) error {
	ret := _mock.Called(ctx, taskId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTask")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, taskId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTaskCrud_DeleteTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTask'
type MockTaskCrud_DeleteTask_Call struct {
	*mock.Call
}

// DeleteTask is a helper method to define mock.On call
//   - ctx context.Context
//   - taskId int
func (_e *MockTaskCrud_Expecter) DeleteTask(ctx interface{}, taskId interface{}) *MockTaskCrud_DeleteTask_Call {
	return &MockTaskCrud_DeleteTask_Call{Call: _e.mock.On("DeleteTask", ctx, taskId)}
}

func (_c *MockTaskCrud_DeleteTask_Call) Run(run func(ctx context.Context, taskId int)) *MockTaskCrud_DeleteTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTaskCrud_DeleteTask_Call) Return(err error) *MockTaskCrud_DeleteTask_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTaskCrud_DeleteTask_Call) RunAndReturn(run func(ctx context.Context, taskId int) error) *MockTaskCrud_DeleteTask_Call {
	_c.Call.Return(run)
	return _c
}

// ReadTaskById provides a mock function for the type MockTaskCrud
func (_mock *MockTaskCrud) ReadTaskById(ctx context.Context, taskId int) (*task_crud.Task, error) {
	ret := _mock.Called(ctx, taskId)

	if len(ret) == 0 {
		panic("no return value specified for ReadTaskById")
	}

	var r0 *task_crud.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*task_crud.Task, error)); ok {
		return returnFunc(ctx, taskId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *task_crud.Task); ok {
		r0 = returnFunc(ctx, taskId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*task_crud.Task)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, taskId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskCrud_ReadTaskById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadTaskById'
type MockTaskCrud_ReadTaskById_Call struct {
	*mock.Call
}

// ReadTaskById is a helper method to define mock.On call
//   - ctx context.Context
//   - taskId int
func (_e *MockTaskCrud_Expecter) ReadTaskById(ctx interface{}, taskId interface{}) *MockTaskCrud_ReadTaskById_Call {
	return &MockTaskCrud_ReadTaskById_Call{Call: _e.mock.On("ReadTaskById", ctx, taskId)}
}

func (_c *MockTaskCrud_ReadTaskById_Call) Run(run func(ctx context.Context, taskId int)) *MockTaskCrud_ReadTaskById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTaskCrud_ReadTaskById_Call) Return(task *task_crud.Task, err error) *MockTaskCrud_ReadTaskById_Call {
	_c.Call.Return(task, err)
	return _c
}

func (_c *MockTaskCrud_ReadTaskById_Call) RunAndReturn(run func(ctx context.Context, taskId int) (*task_crud.Task, error)) *MockTaskCrud_ReadTaskById_Call {
	_c.Call.Return(run)
	return _c
}

// ReadTasks provides a mock function for the type MockTaskCrud
func (_mock *MockTaskCrud) ReadTasks(ctx context.Context) (*[]task_crud.Task, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ReadTasks")
	}

	var r0 *[]task_crud.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*[]task_crud.Task, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *[]task_crud.Task); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]task_crud.Task)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskCrud_ReadTasks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadTasks'
type MockTaskCrud_ReadTasks_Call struct {
	*mock.Call
}

// ReadTasks is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTaskCrud_Expecter) ReadTasks(ctx interface{}) *MockTaskCrud_ReadTasks_Call {
	return &MockTaskCrud_ReadTasks_Call{Call: _e.mock.On("ReadTasks", ctx)}
}

func (_c *MockTaskCrud_ReadTasks_Call) Run(run func(ctx context.Context)) *MockTaskCrud_ReadTasks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTaskCrud_ReadTasks_Call) Return(tasks *[]task_crud.Task, err error) *MockTaskCrud_ReadTasks_Call {
	_c.Call.Return(tasks, err)
	return _c
}

func (_c *MockTaskCrud_ReadTasks_Call) RunAndReturn(run func(ctx context.Context) (*[]task_crud.Task, error)) *MockTaskCrud_ReadTasks_Call {
	_c.Call.Return(run)
	return _c
}

// ReadTasksByUserId provides a mock function for the type MockTaskCrud
func (_mock *MockTaskCrud) ReadTasksByUserId(ctx context.Context, userId *string) (*[]task_crud.Task, error) {
	ret := _mock.Called(ctx, userId)

	if len(ret) == 0 {
		panic("no return value specified for ReadTasksByUserId")
	}

	var r0 *[]task_crud.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *string) (*[]task_crud.Task, error)); ok {
		return returnFunc(ctx, userId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *string) *[]task_crud.Task); ok {
		r0 = returnFunc(ctx, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]task_crud.Task)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *string) error); ok {
		r1 = returnFunc(ctx, userId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskCrud_ReadTasksByUserId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadTasksByUserId'
type MockTaskCrud_ReadTasksByUserId_Call struct {
	*mock.Call
}

// ReadTasksByUserId is a helper method to define mock.On call
//   - ctx context.Context
//   - userId *string
func (_e *MockTaskCrud_Expecter) ReadTasksByUserId(ctx interface{}, userId interface{}) *MockTaskCrud_ReadTasksByUserId_Call {
	return &MockTaskCrud_ReadTasksByUserId_Call{Call: _e.mock.On("ReadTasksByUserId", ctx, userId)}
}

func (_c *MockTaskCrud_ReadTasksByUserId_Call) Run(run func(ctx context.Context, userId *string)) *MockTaskCrud_ReadTasksByUserId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *string
		if args[1] != nil {
			arg1 = args[1].(*string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTaskCrud_ReadTasksByUserId_Call) Return(tasks *[]task_crud.Task, err error) *MockTaskCrud_ReadTasksByUserId_Call {
	_c.Call.Return(tasks, err)
	return _c
}

func (_c *MockTaskCrud_ReadTasksByUserId_Call) RunAndReturn(run func(ctx context.Context, userId *string) (*[]task_crud.Task, error)) *MockTaskCrud_ReadTasksByUserId_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatusTask provides a mock function for the type MockTaskCrud
func (_mock *MockTaskCrud) UpdateStatusTask(ctx context.Context, taskId int, status *string) error {
	ret := _mock.Called(ctx, taskId, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatusTask")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, *string) error); ok {
		r0 = returnFunc(ctx, taskId, status)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTaskCrud_UpdateStatusTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatusTask'
type MockTaskCrud_UpdateStatusTask_Call struct {
	*mock.Call
}

// UpdateStatusTask is a helper method to define mock.On call
//   - ctx context.Context
//   - taskId int
//   - status *string
func (_e *MockTaskCrud_Expecter) UpdateStatusTask(ctx interface{}, taskId interface{}, status interface{}) *MockTaskCrud_UpdateStatusTask_Call {
	return &MockTaskCrud_UpdateStatusTask_Call{Call: _e.mock.On("UpdateStatusTask", ctx, taskId, status)}
}

func (_c *MockTaskCrud_UpdateStatusTask_Call) Run(run func(ctx context.Context, taskId int, status *string)) *MockTaskCrud_UpdateStatusTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 *string
		if args[2] != nil {
			arg2 = args[2].(*string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTaskCrud_UpdateStatusTask_Call) Return(err error) *MockTaskCrud_UpdateStatusTask_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTaskCrud_UpdateStatusTask_Call) RunAndReturn(run func(ctx context.Context, taskId int, status *string) error) *MockTaskCrud_UpdateStatusTask_Call {
	_c.Call.Return(run)
	return _c
}
